version: '3'
services:
  planet_alderaan:
    image: planets/dagobah
    #build: .
    ports:
    - "11311:11311"
    volumes:
    - ${USER}/workspace:/home/yoda/workspace
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    user: yoda